FROM ruby:2.4.2-alpine

RUN apk update && apk add build-base nodejs postgresql-dev

# Configure the main working directory. This is the base
# directory used in any further RUN, COPY, and ENTRYPOINT
# commands.
RUN mkdir -p /app 
WORKDIR /app

# Copy the Gemfile as well as the Gemfile.lock and install
# the RubyGems. This is a separate step so the dependencies
# will be cached unless changes to one of those two files
# are made.
COPY Gemfile Gemfile.lock ./ 
RUN bundle install --jobs 20 --retry 5 --without development test

# Set Rails to run in production
ENV RAILS_ENV production 
ENV RACK_ENV production
ENV LOG_LEVEL warn 
# make the repcompile task run successfully because config/application.rb assumes it has a value (invokes split)
ENV ACTION_CABLE_ALLOWED_REQUEST_ORIGINS https://dummy.com 

# Copy the main application.
COPY . ./

# Precompile Rails assets
RUN bundle exec rake assets:precompile

# Start puma
CMD bundle exec puma -C config/puma.rb